stock_list/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.form import _Auto
from wtforms import StringField,PasswordField,SubmitField,ValidationError
from wtforms.validators import DataRequired,Email,EqualTo
from stock_list.models import User

class LoginForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('ログイン')


class RegistrationForm(FlaskForm):
    username = StringField("ユーザーネーム",validators=[DataRequired()])
    password = PasswordField("パスワード", validators=[DataRequired(), EqualTo("pass_confirm", message="Passwords do not match")])
    pass_confirm = PasswordField("パスワード（確認）",validators=[DataRequired()])
    submit = SubmitField("Sign up")
    
    def validate_username(self,field):
        if User.query.filter_by(username =field.data).first():
            raise ValidationError("This UserName are already take")
        
    
class UpdateUserForm(FlaskForm):
    username = StringField("ユーザーネーム",validators=[DataRequired()])
    password = PasswordField("パスワード",validators=[DataRequired(),EqualTo("pass_confirm","Passwords do not match")])
    pass_confirm = PasswordField("パスワード（確認）")
    submit = SubmitField("更新")
    
    def __init__(self, user_id,*args,**kwargs):
        super(UpdateUserForm,self).__init__(*args,**kwargs)
        self.id =user_id
        
    def validate_username(self,field):
        if User.query.filter(User.id !=self.id).filter_by(username =field.data).first():
            raise ValidationError("This UserName are already take")

stock_list/users/views.py
from flask import Flask,render_template,url_for,redirect,flash,request,abort
from flask_login import  UserMixin, login_user, logout_user, login_required, current_user

from stock_list import db
from stock_list.models import User
from stock_list.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from flask import Blueprint

users=Blueprint('users',__name__)



@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next = request.args.get('next')
                if next == None or not next[0] == '/':
                    next = url_for('main.home')
                return redirect(next)
            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')

    return render_template('users/login.html', form=form)

@users.route("/logout", methods =["GET","POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))
    
@users.route("/register", methods =["GET","POST"])
#本番環境は[@login_required]
def register():
    form = RegistrationForm()
    #if not current_user.is_administrator():
        #abort(403)
    if form.validate_on_submit():
        user = User(username=form.username.data,password=form.password.data,administrator="0")
        db.session.add(user)
        db.session.commit()
        
        flash('ユーザーが登録されました')
        return redirect(url_for("users.user_maintenance"))
    return render_template("users/register.html",form=form)

@users.route("/user_maintenance")
@login_required
def user_maintenance():
    users = User.query.order_by(User.id).all()
    return render_template("users/user_maintenance.html" ,users=users)

@users.route("/<int:user_id>/account",methods =["GET","POST"])
@login_required
def account(user_id):
    user = User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)
    form = UpdateUserForm(user_id)
    if form.validate_on_submit():
        user.username = form.username.data
        if form.password.data:
            user.password = form.password.data

        db.session.commit()
        flash("ユーザーアカウントが更新されました")
        return redirect(url_for("users.user_maintenance"))
    elif request.method == 'GET':
        form.username.data = user.username
    
    return render_template("users/account.html",form=form)
    
@users.route('/<int:user_id>/delete',methods =["GET","POST"]) 
@login_required   
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if not current_user.is_administrator():
        abort(403)
    if  user.is_administrator():
        flash("管理者は削除できません")
        return redirect(url_for("users.account",user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash("ユーザーアカウントが削除されました")
    return redirect(url_for("users.user_maintenance"))

stock_list/templates/users/account.html
{% extends "base.html" %} {% block content%} {% if
current_user.is_administrator() %}
<section id="menu">
  <div class="container my-3 py-4 bg-light">
    <div class="row">
      <div class="col-md-3">
        <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#del_modal">
          Delete
        </button>
      </div>
    </div>
  </div>
</section>
{% endif %}

<section id="user_update">
  <div class="container my-3">
    <div class="row">
      <div class="col-lg-4 mx-auto">
        <div class="card bg-success text-center">
          <div class="card-body text-light">
            <h3>Update user</h3>
            <p>Please change the user information</p>
            <form method="POST">
              {{form.hidden_tag()}}
              <div class="mb-3">
                {{render_field(form.username, class="form-control
                form-control-lg" ,placeholder="Username")}}
              </div>

              <hr />
              <div class="mb-3">
                {{render_field(form.password, class="form-control
                form-control-lg" ,placeholder="New password")}}
              </div>
              <div class="mb-3">
                {{render_field(form.pass_confirm, class="form-control
                form-control-lg" ,placeholder="New password(confirmation）")}}
              </div>
              <button type="submit" class="btn btn-outline-light w-100">
                Update
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="del_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to permanently delete this user?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cancel
        </button>
        <form action="{{url_for('users.delete_user',user_id=form.id)}}" method="POST">
          <input type="submit" class="btn btn-danger" value="delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

stock_list/templates/users/login.html
{% extends "base.html" %} {% block content%}

<section id="menu">
    <div class="container my-3 py-3 bg-light">
        <div class="row">
            <div class="col-md-3">
                <a href="{{ url_for('users.register') }}" class="btn btn-primary w-100">
                    Sign up
                </a>
            </div>
        </div>
    </div>
</section>

<section id="user_register">
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <div class="card bg-primary text-center">
                    <div class="card-body text-light">
                        <h3>Login</h3>
                        <form method="POST">
                            {{form.hidden_tag()}}
                            <div class="mb-3">
                                {{ render_field(form.username,placeholder ="UserName",
                                class="form-control form-control-lg")}}
                            </div>

                            <div class="mb-3">
                                {{ render_field(form.password,placeholder ="Password",
                                class="form-control form-control-lg")}}
                            </div>
                            <div>

                                {{form.submit(class="btn btn-out-line-light w-100",value="Login")}}
                            </div>


                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

{% endblock %}

stock_list/templates/users/register.html
{% extends "base.html" %} {% block content%}

<section id="user_register">
  <div class="container my-5">
    <div class="row">
      <div class="col-lg-4 mx-auto">
        <div class="card bg-primary text-center">
          <div class="card-body text-light">
            <h3>Sign up</h3>
            <p> Enter your new user account information.</p>
            <form method="POST">
              {{form.hidden_tag()}}
              <div class="mb-3">
                {{ render_field(form.username,placeholder ="UserName",
                class="form-control form-control-lg")}}

                <div class="mb-3">
                  {{ render_field(form.password,placeholder ="Password",
                  class="form-control form-control-lg")}}
                </div>
                <div class="mb-3">
                  {{ render_field(form.pass_confirm,placeholder
                  ="password(confirm)", class="form-control form-control-lg")}}
                </div>
                {{form.submit(class="btn btn-out-line-light w-100")}}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

stock_list/templates/users/user_maintenance.html
{% extends "base.html" %}
{% block content %}

<header id="page-header">
    <div class="container my-3 py-3 bg-light">
        <div class="row">
            <div class="col-md-6 m-auto text-center">
                <h1>User Management</h1>
            </div>
        </div>
    </div>
</header>

<body>

    {% if current_user.is_administrator() %}

    <section id="menu">
        <div class="container my-3 py-3 bg-light">
            <div class="row">
                <div class="col-md-3">
                    <a href="{{ url_for('users.register') }}" class="btn btn-primary w-100">
                        create an account
                    </a>
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    <section id="list">
        <div class="container my-3">
            <div class="row">
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">
                            <h4>UserList</h4>
                        </div>
                        <table class="table table-striped">
                            <thead class="table-dark">
                                <tr>
                                    <th>ID</th>
                                    <th>UserName</th>
                                    <th>edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}

                                <tr>
                                    <td>{{user.id}}</td>
                                    <td>{{ user.username }}</td>

                                    <td>
                                        {% if current_user.is_administrator() or current_user.id == user.id%}
                                        <a href="{{ url_for('users.account',user_id=user.id) }}"
                                            class="btn btn-secondary">
                                            Edit
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

</html>

{% endblock %}