stock_list/main/views.py
from flask import Blueprint,render_template,redirect,request,url_for,flash,abort
from flask_login import login_required,current_user
from stock_list.models import TableCategory,Stock
from stock_list.main.forms import TableCategoryForm,UpdateCategoryForm,AddFactorForm,AddQuantityForm,IssueQuantityForm,UpdateStockForm
from stock_list import db

main = Blueprint("main",__name__)

@main.route("/",methods =["GET","POST"])
@login_required
def home():
    table_categories =  TableCategory.query.order_by(TableCategory.id).all()
    form=TableCategoryForm()
    if form.validate_on_submit():
        table_category =TableCategory(category=form.category.data,text=form.text.data)
        db.session.add(table_category)
        db.session.commit()
        flash('表が追加されました')
        return redirect(url_for('main.home'))
    elif form.errors:
        form.category.data=""
        flash(form.errors['category'][0])
    
    return render_template("home.html",table_categories=table_categories,form=form)

@main.route("/<int:table_category_id>/table_category>",methods =["GET","POST"])
@login_required
def table_category(table_category_id):
    if not current_user.is_administrator():
        abort(403)
    table_category = TableCategory.query.get_or_404(table_category_id)
    form = UpdateCategoryForm(table_category_id)
    if form.validate_on_submit():
        table_category.category = form.category.data
        table_category.text=form.text.data
        db.session.commit()
        flash('カテゴリが更新されました')
        return redirect(url_for('main.home'))
    elif request.method == "GET":
        form.category.data = table_category.category
        form.text.data = table_category.text
    return render_template('table_category.html',form=form)




@main.route("/<int:table_category_id>/delete_category",methods =["GET","POST"])
@login_required
def delete_category(table_category_id):
    if not current_user.is_administrator():
        abort(403)
    table_category = TableCategory.query.get_or_404(table_category_id)
    stock=Stock.query.filter_by(category_id=table_category_id).all()
    db.session.delete(table_category,stock)
    db.session.commit()
    flash('カテゴリが削除されました')
    return redirect(url_for('main.home'))

@main.route("/<int:table_category_id>/table",methods =["GET","POST"])
@login_required
def table(table_category_id):
    stocks = Stock.query.filter_by(category_id=table_category_id).all()
    category =TableCategory.query.get_or_404(table_category_id)
    form = AddFactorForm(category_id=table_category_id)
    if form.validate_on_submit():
        stock =Stock(stock_name=form.stock_name.data,quantity=form.quantity.data,category_id=table_category_id)
        db.session.add(stock)
        db.session.commit()
        flash('アイテムが追加されました')
        return redirect(url_for('main.table',table_category_id=table_category_id))
    elif form.errors:
        form.stock_name.data=""
        flash(form.errors['stock_name'][0]) 
    
    return render_template("table.html",stocks=stocks,form=form,category=category)

@main.route("/<int:stock_id>/update_stock>",methods =["GET","POST"])
@login_required
def update_stock(stock_id):
    if not current_user.is_administrator():
        abort(403)
    stock = Stock.query.get_or_404(stock_id)
    form = UpdateStockForm(stock_id)
    table_category_id=stock.category_id
    stock_id=stock_id
    if form.validate_on_submit():
        stock.stock_name = form.stock_name.data
        stock.quantity=form.quantity.data
        db.session.commit()
        flash('ストック情報が更新されました')
        return redirect(url_for('main.table',table_category_id=table_category_id))
    elif request.method == "GET":
        form.stock_name.data = stock.stock_name
        form.quantity.data = stock.quantity
    return render_template('update_stock.html',form=form,stock_id=stock_id)



@main.route("/<int:stock_id>/delete_stock",methods =["GET","POST"])
@login_required
def delete_stock(stock_id):
    if not current_user.is_administrator():
        abort(403)
    stock = Stock.query.get_or_404(stock_id)
    table_category_id=stock.category_id
    db.session.delete(stock)
    db.session.commit()
    flash('ストックが削除されました')
    return redirect(url_for('main.table',table_category_id=table_category_id))


@main.route("/<int:stock_id>/add_quantity",methods =["GET","POST"])
@login_required
def add_quantity(stock_id):
    stock = Stock.query.filter_by(id=stock_id).first_or_404()
    existing_quantity=stock.quantity
    table_category_id=stock.category_id
    form = AddQuantityForm()
    if form.validate_on_submit():
        new_quantity =form.quantity.data + existing_quantity
        stock.quantity = new_quantity
        db.session.commit()
        flash('アイテムが追加されました')
        return redirect(url_for('main.table',table_category_id=table_category_id))
    return render_template("add_quantity.html",stock=stock,form=form)

@main.route("/<int:stock_id>/issue_stock",methods =["GET","POST"])
@login_required
def issue_stock(stock_id):
    stock = Stock.query.filter_by(id=stock_id).first_or_404()
    existing_quantity=stock.quantity
    table_category_id=stock.category_id
    form = IssueQuantityForm()
    if form.validate_on_submit():
        new_quantity =existing_quantity - form.quantity.data
        stock.quantity = new_quantity
        db.session.commit()
        flash('アイテムが出庫されました')
        return redirect(url_for('main.table',table_category_id=table_category_id))
    return render_template("issue_stock.html",stock=stock,form=form)

#受け取ったquantityを元の在庫の値に足してdb.commitで行けるはず

stock_list/users/views.py
from flask import Flask,render_template,url_for,redirect,flash,request,abort
from flask_login import  UserMixin, login_user, logout_user, login_required, current_user

from stock_list import db
from stock_list.models import User
from stock_list.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from flask import Blueprint

users=Blueprint('users',__name__)



@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next = request.args.get('next')
                if next == None or not next[0] == '/':
                    next = url_for('main.home')
                return redirect(next)
            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')

    return render_template('users/login.html', form=form)

@users.route("/logout", methods =["GET","POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))
    
@users.route("/register", methods =["GET","POST"])
#本番環境は[@login_required]
def register():
    form = RegistrationForm()
    #if not current_user.is_administrator():
        #abort(403)
    if form.validate_on_submit():
        user = User(username=form.username.data,password=form.password.data,administrator="0")
        db.session.add(user)
        db.session.commit()
        
        flash('ユーザーが登録されました')
        return redirect(url_for("users.user_maintenance"))
    return render_template("users/register.html",form=form)

@users.route("/user_maintenance")
@login_required
def user_maintenance():
    users = User.query.order_by(User.id).all()
    return render_template("users/user_maintenance.html" ,users=users)

@users.route("/<int:user_id>/account",methods =["GET","POST"])
@login_required
def account(user_id):
    user = User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)
    form = UpdateUserForm(user_id)
    if form.validate_on_submit():
        user.username = form.username.data
        if form.password.data:
            user.password = form.password.data

        db.session.commit()
        flash("ユーザーアカウントが更新されました")
        return redirect(url_for("users.user_maintenance"))
    elif request.method == 'GET':
        form.username.data = user.username
    
    return render_template("users/account.html",form=form)
    
@users.route('/<int:user_id>/delete',methods =["GET","POST"]) 
@login_required   
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if not current_user.is_administrator():
        abort(403)
    if  user.is_administrator():
        flash("管理者は削除できません")
        return redirect(url_for("users.account",user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash("ユーザーアカウントが削除されました")
    return redirect(url_for("users.user_maintenance"))

stock_list/templates/_formhelpers.html
{% macro render_field(field) %}
{{ field(**kwargs)|safe }}
{% if field.errors %}
<br>
{% for error in field.errors %}
{{ error }}
{% endfor %}
{% endif %}
{% endmacro %}

stock_list/templates/add_quantity.html
{% extends "base.html" %} {% block content%}
<h1>Is this the right stock to add?</h1>
<div class="row">
    <div class="col-md-8">
        <div class="panel-heading my-2"></div>

        <table class="table" name="現在の在庫">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">StockName</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Manage</th>

                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>{{ stock.id }}</td>
                    <td>{{ stock.stock_name }}</td>
                    <td>{{ stock.quantity }}</td>
                </tr>

            </tbody>

        </table>

        <div class="input-group">

            <form method="POST">
                {{form.hidden_tag()}}
                <div class="modal-body">
                    {{form.quantity.label(class="form-control-label")}}
                    {{form.quantity(class="form-control")}}


                </div>
                <div class="modal-footer">
                    {{form.submit(class="btn btn-warning")}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stock_list/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <title>Yossy Inc.</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('main.home')}}">StockList</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ms-auto">

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.home')}}">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.user_maintenance')}}">User</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
          </li>
          <span class="navbar-text ms-3">logging in</span>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% from "_formhelpers.html" import render_field %}

  <div class="container" style="padding-top: 4rem; padding-bottom: 4rem">
    {% for message in get_flashed_messages()%}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %} {% block content%} {% endblock %}
  </div>

  <footer id="footer" class="footer text-center pt-2 bg-dark fixed-bottom">
    <div class="container">
      <div class="row">
        <div class="col text-white">
          <p>Alphajiri limited</p>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

stock_list/templates/home.html
{% extends "base.html" %} {% block content%}



<div class="main my-5">
    <h1 class="display-6">Please choose category</h1>
</div>

<div class="">
    <section>
        <div class="container my-3 py-3 bg-light">
            <div class="row">
                <div class="col-md-3">
                    <button type="button" class="btn btn-warning w-100" data-bs-toggle="modal"
                        data-bs-target="#addCategoryModal">
                        Add category
                    </button>
                </div>
            </div>
        </div>
    </section>

    <div class="row mt-100">

        <div class="col-md-4">
            <div class="card">


                {% for table_category in table_categories%}
                <div class="card-body">
                    <h5 class="card-title">
                        {{table_category.category}}
                    </h5>
                    <p class="card-text">{{table_category.text}}</p>
                    {% if current_user.is_administrator() %}<a
                        href="{{ url_for('main.table_category',table_category_id=table_category.id)}}"
                        class="btn btn-primary">Edit</a>
                    {% endif %}
                    <a href="{{ url_for('main.table', table_category_id=table_category.id) }}"
                        class="btn btn-secondary">

                        details
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>



        <!--Modal-->
        <div class="modal fade" id="addCategoryModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header bg-warning">
                        <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="POST">
                        {{form.hidden_tag()}}
                        <div class="modal-body">
                            {{form.category.label(class="form-control-label")}}
                            {{form.category(class="form-control")}}
                            {{form.text.label(class="form-control-label")}}
                            {{form.text(class="form-control")}}
                        </div>
                        <div class="modal-footer">
                            {{form.submit(class="btn btn-warning")}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

stock_list/templates/issue_stock.html
{% extends "base.html" %} {% block content%}

<h1>Is this the right stock to issue?</h1>
<div class="row">
    <div class="col-md-8">
        <div class="panel-heading my-2"></div>

        <table class="table" name="現在の在庫">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">StockName</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Manage</th>

                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>{{ stock.id }}</td>
                    <td>{{ stock.stock_name }}</td>
                    <td>{{ stock.quantity }}</td>
                </tr>

            </tbody>

        </table>


        <div class="input-group">

            <form method="POST">
                {{form.hidden_tag()}}
                <div class="modal-body">
                    {{form.quantity.label(class="form-control-label")}}
                    {{form.quantity(class="form-control")}}


                </div>
                <div class="modal-footer">
                    {{form.submit(class="btn btn-warning")}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stock_list/templates/table.html
{% extends "base.html" %} {% block content%}

<body>
  <h1 class="my-5">{{category.category}}</h1>

  <section>
    <div class="container my-3 py-3 bg-light">
      <div class="row">
        <div class="col-md-3">
          <button type="button" class="btn btn-warning w-100" data-bs-toggle="modal" data-bs-target="#addCategoryModal">
            Increase the types of stock
          </button>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">No</th>
              <th scope="col">StockName</th>
              <th scope="col">Quantity</th>
              <th scope="col">Manage</th>

            </tr>
          </thead>



          <tbody>
            {% for stock in stocks %}
            <tr>
              <td>{{loop.index}}</td>
              <td>{{ stock.stock_name }}</td>
              <td>{{ stock.quantity }}</td>
              <td>
                <a href="{{ url_for('main.add_quantity',stock_id=stock.id)}}" class="btn btn-secondary">
                  Add
                </a>
                <a href="{{ url_for('main.issue_stock',stock_id=stock.id)}}" class="btn btn-secondary">
                  Issue
                </a>
                {% if current_user.is_administrator() %}<a href="{{ url_for('main.update_stock',stock_id=stock.id)}}"
                  class="btn btn-primary">Edit</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}


          </tbody>
        </table>
      </div>
    </div>


    <div class="modal fade" id="addCategoryModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header bg-warning">
            <h5 class="modal-title" id="exampleModalLabel">Increase the types of stock</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="POST">
            {{form.hidden_tag()}}
            <div class="modal-body">
              {{form.stock_name.label(class="form-control-label")}}
              {{form.stock_name(class="form-control")}}
              {{form.quantity.label(class="form-control-label")}}
              {{form.quantity(class="form-control")}}


            </div>
            <div class="modal-footer">
              {{form.submit(class="btn btn-warning")}}
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</body>

{% endblock %}

stock_list/templates/table_category.html
{% extends "base.html" %} {% block content%} {% if
current_user.is_administrator() %}
<section id="menu">
    <div class="container my-3 py-4 bg-light">
        <div class="row">
            <div class="col-md-3">
                <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#del_modal">
                    Delete
                </button>
            </div>
        </div>
    </div>
</section>
{% endif %}

<section id="category_update">
    <div class="container my-3">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <div class="card bg-success text-center">
                    <div class="card-body text-light">
                        <h3>Category Update</h3>
                        <p>Please change the category</p>
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <div class="mb-3">
                                {{render_field(form.category, class="form-control
                                form-control-lg" ,placeholder="カテゴリ名")}}
                            </div>

                            <hr />
                            <div class="mb-3">
                                {{render_field(form.text, class="form-control
                                form-control-lg" ,placeholder="説明文")}}
                            </div>

                            {{ form.submit(class="btn btn-outline-light w-100")}}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="del_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>このカテゴリを削除しますか？</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    キャンセル
                </button>
                <form action="{{url_for('main.delete_category',table_category_id=form.id)}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="削除" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

stock_list/templates/update_stock.html
{% extends "base.html" %} {% block content%} {% if
current_user.is_administrator() %}
<section id="menu">
    <div class="container my-3 py-4 bg-light">
        <div class="row">
            <div class="col-md-3">
                <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#del_modal">
                    Delete
                </button>
            </div>
        </div>
    </div>
</section>
{% endif %}

<section id="category_update">
    <div class="container my-3">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <div class="card bg-success text-center">
                    <div class="card-body text-light">
                        <h3>Update Stock</h3>
                        <p>Please change stock name.</p>
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <div class="mb-3">
                                {{render_field(form.stock_name, class="form-control
                                form-control-lg" ,placeholder="StockName")}}
                            </div>

                            <hr />
                            <div class="mb-3">
                                {{render_field(form.quantity, class="form-control
                                form-control-lg" ,placeholder="quantity")}}
                            </div>

                            {{ form.submit(class="btn btn-outline-light w-100")}}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="del_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>May I remove this stock name？</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Cancel
                </button>
                <form action="{{url_for('main.delete_stock',stock_id=stock_id)}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="削除" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}